// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/sshproxy/v1/control_plane.proto

package sshproxyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceID) Reset() {
	*x = ResourceID{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceID) ProtoMessage() {}

func (x *ResourceID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceID.ProtoReflect.Descriptor instead.
func (*ResourceID) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *PageInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type OperationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *OperationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SystemHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DataPlane     string                 `protobuf:"bytes,2,opt,name=data_plane,json=dataPlane,proto3" json:"data_plane,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemHealth) Reset() {
	*x = SystemHealth{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemHealth) ProtoMessage() {}

func (x *SystemHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemHealth.ProtoReflect.Descriptor instead.
func (*SystemHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *SystemHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SystemHealth) GetDataPlane() string {
	if x != nil {
		return x.DataPlane
	}
	return ""
}

func (x *SystemHealth) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemHealth) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SourceIp      string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	TargetHost    string                 `protobuf:"bytes,4,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    int32                  `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      string                 `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	BytesIn       int64                  `protobuf:"varint,8,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut      int64                  `protobuf:"varint,9,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	RecordingFile string                 `protobuf:"bytes,11,opt,name=recording_file,json=recordingFile,proto3" json:"recording_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Session) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *Session) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *Session) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *Session) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Session) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Session) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *Session) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetRecordingFile() string {
	if x != nil {
		return x.RecordingFile
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListSessionsRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListSessionsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ListSessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSessionsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type SessionRecordingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RecordingFile string                 `protobuf:"bytes,2,opt,name=recording_file,json=recordingFile,proto3" json:"recording_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRecordingMetadata) Reset() {
	*x = SessionRecordingMetadata{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRecordingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRecordingMetadata) ProtoMessage() {}

func (x *SessionRecordingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRecordingMetadata.ProtoReflect.Descriptor instead.
func (*SessionRecordingMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *SessionRecordingMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRecordingMetadata) GetRecordingFile() string {
	if x != nil {
		return x.RecordingFile
	}
	return ""
}

type RecordingContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingContent) Reset() {
	*x = RecordingContent{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingContent) ProtoMessage() {}

func (x *RecordingContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingContent.ProtoReflect.Descriptor instead.
func (*RecordingContent) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *RecordingContent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RecordingContent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RecordingContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MfaEnabled    bool                   `protobuf:"varint,6,opt,name=mfa_enabled,json=mfaEnabled,proto3" json:"mfa_enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,10,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetMfaEnabled() bool {
	if x != nil {
		return x.MfaEnabled
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Healthy       bool                   `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Maintenance   bool                   `protobuf:"varint,8,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	Weight        int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	MaxSessions   int32                  `protobuf:"varint,10,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	Sessions      int32                  `protobuf:"varint,11,opt,name=sessions,proto3" json:"sessions,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Server) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Server) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *Server) GetMaintenance() bool {
	if x != nil {
		return x.Maintenance
	}
	return false
}

func (x *Server) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Server) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *Server) GetSessions() int32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

func (x *Server) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Server) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{15}
}

func (x *ListServersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListServersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{16}
}

func (x *ListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ListServersResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type CreateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{17}
}

func (x *CreateServerRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateServerRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *UpdateServerRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ServerHealthSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Healthy       int32                  `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Unhealthy     int32                  `protobuf:"varint,3,opt,name=unhealthy,proto3" json:"unhealthy,omitempty"`
	Maintenance   int32                  `protobuf:"varint,4,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHealthSummary) Reset() {
	*x = ServerHealthSummary{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHealthSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHealthSummary) ProtoMessage() {}

func (x *ServerHealthSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHealthSummary.ProtoReflect.Descriptor instead.
func (*ServerHealthSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{19}
}

func (x *ServerHealthSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ServerHealthSummary) GetHealthy() int32 {
	if x != nil {
		return x.Healthy
	}
	return 0
}

func (x *ServerHealthSummary) GetUnhealthy() int32 {
	if x != nil {
		return x.Unhealthy
	}
	return 0
}

func (x *ServerHealthSummary) GetMaintenance() int32 {
	if x != nil {
		return x.Maintenance
	}
	return 0
}

type ConfigDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *structpb.Struct       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDocument) Reset() {
	*x = ConfigDocument{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDocument) ProtoMessage() {}

func (x *ConfigDocument) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDocument.ProtoReflect.Descriptor instead.
func (*ConfigDocument) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigDocument) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *structpb.Struct       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateConfigRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigVersionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVersionMetadata) Reset() {
	*x = ConfigVersionMetadata{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersionMetadata) ProtoMessage() {}

func (x *ConfigVersionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersionMetadata.ProtoReflect.Descriptor instead.
func (*ConfigVersionMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{22}
}

func (x *ConfigVersionMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigVersionMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ConfigVersionMetadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListConfigVersionsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Versions      []*ConfigVersionMetadata `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigVersionsResponse) Reset() {
	*x = ListConfigVersionsResponse{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigVersionsResponse) ProtoMessage() {}

func (x *ListConfigVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{23}
}

func (x *ListConfigVersionsResponse) GetVersions() []*ConfigVersionMetadata {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetConfigVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigVersionRequest) Reset() {
	*x = GetConfigVersionRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigVersionRequest) ProtoMessage() {}

func (x *GetConfigVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigVersionRequest.ProtoReflect.Descriptor instead.
func (*GetConfigVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{24}
}

func (x *GetConfigVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ConfigVersionContent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*ConfigVersionContent_Config
	//	*ConfigVersionContent_RawContent
	Content       isConfigVersionContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVersionContent) Reset() {
	*x = ConfigVersionContent{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersionContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersionContent) ProtoMessage() {}

func (x *ConfigVersionContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersionContent.ProtoReflect.Descriptor instead.
func (*ConfigVersionContent) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{25}
}

func (x *ConfigVersionContent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigVersionContent) GetContent() isConfigVersionContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ConfigVersionContent) GetConfig() *structpb.Struct {
	if x != nil {
		if x, ok := x.Content.(*ConfigVersionContent_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ConfigVersionContent) GetRawContent() string {
	if x != nil {
		if x, ok := x.Content.(*ConfigVersionContent_RawContent); ok {
			return x.RawContent
		}
	}
	return ""
}

type isConfigVersionContent_Content interface {
	isConfigVersionContent_Content()
}

type ConfigVersionContent_Config struct {
	Config *structpb.Struct `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

type ConfigVersionContent_RawContent struct {
	RawContent string `protobuf:"bytes,3,opt,name=raw_content,json=rawContent,proto3,oneof"`
}

func (*ConfigVersionContent_Config) isConfigVersionContent_Content() {}

func (*ConfigVersionContent_RawContent) isConfigVersionContent_Content() {}

type RollbackConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackConfigRequest) Reset() {
	*x = RollbackConfigRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigRequest) ProtoMessage() {}

func (x *RollbackConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigRequest.ProtoReflect.Descriptor instead.
func (*RollbackConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{26}
}

func (x *RollbackConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CAPublicKeys struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserCaPublicKey string                 `protobuf:"bytes,1,opt,name=user_ca_public_key,json=userCaPublicKey,proto3" json:"user_ca_public_key,omitempty"`
	HostCaPublicKey string                 `protobuf:"bytes,2,opt,name=host_ca_public_key,json=hostCaPublicKey,proto3" json:"host_ca_public_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CAPublicKeys) Reset() {
	*x = CAPublicKeys{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAPublicKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAPublicKeys) ProtoMessage() {}

func (x *CAPublicKeys) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAPublicKeys.ProtoReflect.Descriptor instead.
func (*CAPublicKeys) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{27}
}

func (x *CAPublicKeys) GetUserCaPublicKey() string {
	if x != nil {
		return x.UserCaPublicKey
	}
	return ""
}

func (x *CAPublicKeys) GetHostCaPublicKey() string {
	if x != nil {
		return x.HostCaPublicKey
	}
	return ""
}

type SignUserCertificateRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	PublicKey       string                  `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Principals      []string                `protobuf:"bytes,2,rep,name=principals,proto3" json:"principals,omitempty"`
	Ttl             string                  `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ForceCommand    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=force_command,json=forceCommand,proto3" json:"force_command,omitempty"`
	SourceAddresses []string                `protobuf:"bytes,5,rep,name=source_addresses,json=sourceAddresses,proto3" json:"source_addresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignUserCertificateRequest) Reset() {
	*x = SignUserCertificateRequest{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUserCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUserCertificateRequest) ProtoMessage() {}

func (x *SignUserCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUserCertificateRequest.ProtoReflect.Descriptor instead.
func (*SignUserCertificateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{28}
}

func (x *SignUserCertificateRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SignUserCertificateRequest) GetPrincipals() []string {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (x *SignUserCertificateRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *SignUserCertificateRequest) GetForceCommand() *wrapperspb.StringValue {
	if x != nil {
		return x.ForceCommand
	}
	return nil
}

func (x *SignUserCertificateRequest) GetSourceAddresses() []string {
	if x != nil {
		return x.SourceAddresses
	}
	return nil
}

type SignedCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   string                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Serial        uint64                 `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedCertificate) Reset() {
	*x = SignedCertificate{}
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCertificate) ProtoMessage() {}

func (x *SignedCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCertificate.ProtoReflect.Descriptor instead.
func (*SignedCertificate) Descriptor() ([]byte, []int) {
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP(), []int{29}
}

func (x *SignedCertificate) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *SignedCertificate) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *SignedCertificate) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignedCertificate) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_api_proto_sshproxy_v1_control_plane_proto protoreflect.FileDescriptor

const file_api_proto_sshproxy_v1_control_plane_proto_rawDesc = "" +
	"\n" +
	")api/proto/sshproxy/v1/control_plane.proto\x12\vsshproxy.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1c\n" +
	"\n" +
	"ResourceID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\bPageInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"+\n" +
	"\x0fOperationStatus\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa6\x01\n" +
	"\fSystemHealth\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"data_plane\x18\x02 \x01(\tR\tdataPlane\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe2\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vtarget_host\x18\x04 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\x05R\n" +
	"targetPort\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x1a\n" +
	"\bduration\x18\a \x01(\tR\bduration\x12\x19\n" +
	"\bbytes_in\x18\b \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\t \x01(\x03R\bbytesOut\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12%\n" +
	"\x0erecording_file\x18\v \x01(\tR\rrecordingFile\"\x80\x01\n" +
	"\x13ListSessionsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x05 \x01(\x05R\aperPage\"s\n" +
	"\x14ListSessionsResponse\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.sshproxy.v1.SessionR\bsessions\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.sshproxy.v1.PageInfoR\x04page\"`\n" +
	"\x18SessionRecordingMetadata\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0erecording_file\x18\x02 \x01(\tR\rrecordingFile\"k\n" +
	"\x10RecordingContent\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\xfc\x02\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1f\n" +
	"\vmfa_enabled\x18\x06 \x01(\bR\n" +
	"mfaEnabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"last_login\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x1f\n" +
	"\vallowed_ips\x18\n" +
	" \x03(\tR\n" +
	"allowedIps\"A\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"g\n" +
	"\x11ListUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.sshproxy.v1.UserR\x05users\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.sshproxy.v1.PageInfoR\x04page\"V\n" +
	"\x11CreateUserRequest\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.sshproxy.v1.UserR\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"w\n" +
	"\x11UpdateUserRequest\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.sshproxy.v1.UserR\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\xbc\x03\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\x12 \n" +
	"\vmaintenance\x18\b \x01(\bR\vmaintenance\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12!\n" +
	"\fmax_sessions\x18\n" +
	" \x01(\x05R\vmaxSessions\x12\x1a\n" +
	"\bsessions\x18\v \x01(\x05R\bsessions\x121\n" +
	"\x04tags\x18\f \x03(\v2\x1d.sshproxy.v1.Server.TagsEntryR\x04tags\x129\n" +
	"\n" +
	"checked_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x12ListServersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"o\n" +
	"\x13ListServersResponse\x12-\n" +
	"\aservers\x18\x01 \x03(\v2\x13.sshproxy.v1.ServerR\aservers\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.sshproxy.v1.PageInfoR\x04page\"B\n" +
	"\x13CreateServerRequest\x12+\n" +
	"\x06server\x18\x01 \x01(\v2\x13.sshproxy.v1.ServerR\x06server\"\x7f\n" +
	"\x13UpdateServerRequest\x12+\n" +
	"\x06server\x18\x01 \x01(\v2\x13.sshproxy.v1.ServerR\x06server\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x85\x01\n" +
	"\x13ServerHealthSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\x05R\ahealthy\x12\x1c\n" +
	"\tunhealthy\x18\x03 \x01(\x05R\tunhealthy\x12 \n" +
	"\vmaintenance\x18\x04 \x01(\x05R\vmaintenance\"A\n" +
	"\x0eConfigDocument\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\"F\n" +
	"\x13UpdateConfigRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\"\x7f\n" +
	"\x15ConfigVersionMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\\\n" +
	"\x1aListConfigVersionsResponse\x12>\n" +
	"\bversions\x18\x01 \x03(\v2\".sshproxy.v1.ConfigVersionMetadataR\bversions\"3\n" +
	"\x17GetConfigVersionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x91\x01\n" +
	"\x14ConfigVersionContent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x00R\x06config\x12!\n" +
	"\vraw_content\x18\x03 \x01(\tH\x00R\n" +
	"rawContentB\t\n" +
	"\acontent\"1\n" +
	"\x15RollbackConfigRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"h\n" +
	"\fCAPublicKeys\x12+\n" +
	"\x12user_ca_public_key\x18\x01 \x01(\tR\x0fuserCaPublicKey\x12+\n" +
	"\x12host_ca_public_key\x18\x02 \x01(\tR\x0fhostCaPublicKey\"\xdb\x01\n" +
	"\x1aSignUserCertificateRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1e\n" +
	"\n" +
	"principals\x18\x02 \x03(\tR\n" +
	"principals\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\tR\x03ttl\x12A\n" +
	"\rforce_command\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\fforceCommand\x12)\n" +
	"\x10source_addresses\x18\x05 \x03(\tR\x0fsourceAddresses\"\x83\x01\n" +
	"\x11SignedCertificate\x12 \n" +
	"\vcertificate\x18\x01 \x01(\tR\vcertificate\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\x04R\x06serial\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt2O\n" +
	"\rSystemService\x12>\n" +
	"\tGetHealth\x12\x16.google.protobuf.Empty\x1a\x19.sshproxy.v1.SystemHealth2\x93\x03\n" +
	"\x0eSessionService\x12S\n" +
	"\fListSessions\x12 .sshproxy.v1.ListSessionsRequest\x1a!.sshproxy.v1.ListSessionsResponse\x12;\n" +
	"\n" +
	"GetSession\x12\x17.sshproxy.v1.ResourceID\x1a\x14.sshproxy.v1.Session\x12D\n" +
	"\vKillSession\x12\x17.sshproxy.v1.ResourceID\x1a\x1c.sshproxy.v1.OperationStatus\x12U\n" +
	"\x13GetSessionRecording\x12\x17.sshproxy.v1.ResourceID\x1a%.sshproxy.v1.SessionRecordingMetadata\x12R\n" +
	"\x18DownloadSessionRecording\x12\x17.sshproxy.v1.ResourceID\x1a\x1d.sshproxy.v1.RecordingContent2\xd7\x02\n" +
	"\vUserService\x12J\n" +
	"\tListUsers\x12\x1d.sshproxy.v1.ListUsersRequest\x1a\x1e.sshproxy.v1.ListUsersResponse\x125\n" +
	"\aGetUser\x12\x17.sshproxy.v1.ResourceID\x1a\x11.sshproxy.v1.User\x12?\n" +
	"\n" +
	"CreateUser\x12\x1e.sshproxy.v1.CreateUserRequest\x1a\x11.sshproxy.v1.User\x12?\n" +
	"\n" +
	"UpdateUser\x12\x1e.sshproxy.v1.UpdateUserRequest\x1a\x11.sshproxy.v1.User\x12C\n" +
	"\n" +
	"DeleteUser\x12\x17.sshproxy.v1.ResourceID\x1a\x1c.sshproxy.v1.OperationStatus2\xbf\x03\n" +
	"\rServerService\x12P\n" +
	"\vListServers\x12\x1f.sshproxy.v1.ListServersRequest\x1a .sshproxy.v1.ListServersResponse\x129\n" +
	"\tGetServer\x12\x17.sshproxy.v1.ResourceID\x1a\x13.sshproxy.v1.Server\x12E\n" +
	"\fCreateServer\x12 .sshproxy.v1.CreateServerRequest\x1a\x13.sshproxy.v1.Server\x12E\n" +
	"\fUpdateServer\x12 .sshproxy.v1.UpdateServerRequest\x1a\x13.sshproxy.v1.Server\x12E\n" +
	"\fDeleteServer\x12\x17.sshproxy.v1.ResourceID\x1a\x1c.sshproxy.v1.OperationStatus\x12L\n" +
	"\x10GetHealthSummary\x12\x16.google.protobuf.Empty\x1a .sshproxy.v1.ServerHealthSummary2\xef\x03\n" +
	"\rConfigService\x12@\n" +
	"\tGetConfig\x12\x16.google.protobuf.Empty\x1a\x1b.sshproxy.v1.ConfigDocument\x12N\n" +
	"\fUpdateConfig\x12 .sshproxy.v1.UpdateConfigRequest\x1a\x1c.sshproxy.v1.OperationStatus\x12U\n" +
	"\x12ListConfigVersions\x12\x16.google.protobuf.Empty\x1a'.sshproxy.v1.ListConfigVersionsResponse\x12[\n" +
	"\x10GetConfigVersion\x12$.sshproxy.v1.GetConfigVersionRequest\x1a!.sshproxy.v1.ConfigVersionContent\x12R\n" +
	"\x0eRollbackConfig\x12\".sshproxy.v1.RollbackConfigRequest\x1a\x1c.sshproxy.v1.OperationStatus\x12D\n" +
	"\fReloadConfig\x12\x16.google.protobuf.Empty\x1a\x1c.sshproxy.v1.OperationStatus2\xc3\x01\n" +
	"\x1bCertificateAuthorityService\x12^\n" +
	"\x13SignUserCertificate\x12'.sshproxy.v1.SignUserCertificateRequest\x1a\x1e.sshproxy.v1.SignedCertificate\x12D\n" +
	"\x0fGetCAPublicKeys\x12\x16.google.protobuf.Empty\x1a\x19.sshproxy.v1.CAPublicKeysBKZIgithub.com/ssh-proxy-core/ssh-proxy-core/api/proto/sshproxy/v1;sshproxyv1b\x06proto3"

var (
	file_api_proto_sshproxy_v1_control_plane_proto_rawDescOnce sync.Once
	file_api_proto_sshproxy_v1_control_plane_proto_rawDescData []byte
)

func file_api_proto_sshproxy_v1_control_plane_proto_rawDescGZIP() []byte {
	file_api_proto_sshproxy_v1_control_plane_proto_rawDescOnce.Do(func() {
		file_api_proto_sshproxy_v1_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sshproxy_v1_control_plane_proto_rawDesc), len(file_api_proto_sshproxy_v1_control_plane_proto_rawDesc)))
	})
	return file_api_proto_sshproxy_v1_control_plane_proto_rawDescData
}

var file_api_proto_sshproxy_v1_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_api_proto_sshproxy_v1_control_plane_proto_goTypes = []any{
	(*ResourceID)(nil),                 // 0: sshproxy.v1.ResourceID
	(*PageInfo)(nil),                   // 1: sshproxy.v1.PageInfo
	(*OperationStatus)(nil),            // 2: sshproxy.v1.OperationStatus
	(*SystemHealth)(nil),               // 3: sshproxy.v1.SystemHealth
	(*Session)(nil),                    // 4: sshproxy.v1.Session
	(*ListSessionsRequest)(nil),        // 5: sshproxy.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),       // 6: sshproxy.v1.ListSessionsResponse
	(*SessionRecordingMetadata)(nil),   // 7: sshproxy.v1.SessionRecordingMetadata
	(*RecordingContent)(nil),           // 8: sshproxy.v1.RecordingContent
	(*User)(nil),                       // 9: sshproxy.v1.User
	(*ListUsersRequest)(nil),           // 10: sshproxy.v1.ListUsersRequest
	(*ListUsersResponse)(nil),          // 11: sshproxy.v1.ListUsersResponse
	(*CreateUserRequest)(nil),          // 12: sshproxy.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),          // 13: sshproxy.v1.UpdateUserRequest
	(*Server)(nil),                     // 14: sshproxy.v1.Server
	(*ListServersRequest)(nil),         // 15: sshproxy.v1.ListServersRequest
	(*ListServersResponse)(nil),        // 16: sshproxy.v1.ListServersResponse
	(*CreateServerRequest)(nil),        // 17: sshproxy.v1.CreateServerRequest
	(*UpdateServerRequest)(nil),        // 18: sshproxy.v1.UpdateServerRequest
	(*ServerHealthSummary)(nil),        // 19: sshproxy.v1.ServerHealthSummary
	(*ConfigDocument)(nil),             // 20: sshproxy.v1.ConfigDocument
	(*UpdateConfigRequest)(nil),        // 21: sshproxy.v1.UpdateConfigRequest
	(*ConfigVersionMetadata)(nil),      // 22: sshproxy.v1.ConfigVersionMetadata
	(*ListConfigVersionsResponse)(nil), // 23: sshproxy.v1.ListConfigVersionsResponse
	(*GetConfigVersionRequest)(nil),    // 24: sshproxy.v1.GetConfigVersionRequest
	(*ConfigVersionContent)(nil),       // 25: sshproxy.v1.ConfigVersionContent
	(*RollbackConfigRequest)(nil),      // 26: sshproxy.v1.RollbackConfigRequest
	(*CAPublicKeys)(nil),               // 27: sshproxy.v1.CAPublicKeys
	(*SignUserCertificateRequest)(nil), // 28: sshproxy.v1.SignUserCertificateRequest
	(*SignedCertificate)(nil),          // 29: sshproxy.v1.SignedCertificate
	nil,                                // 30: sshproxy.v1.Server.TagsEntry
	(*timestamppb.Timestamp)(nil),      // 31: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),      // 32: google.protobuf.FieldMask
	(*structpb.Struct)(nil),            // 33: google.protobuf.Struct
	(*wrapperspb.StringValue)(nil),     // 34: google.protobuf.StringValue
	(*emptypb.Empty)(nil),              // 35: google.protobuf.Empty
}
var file_api_proto_sshproxy_v1_control_plane_proto_depIdxs = []int32{
	31, // 0: sshproxy.v1.SystemHealth.timestamp:type_name -> google.protobuf.Timestamp
	31, // 1: sshproxy.v1.Session.start_time:type_name -> google.protobuf.Timestamp
	4,  // 2: sshproxy.v1.ListSessionsResponse.sessions:type_name -> sshproxy.v1.Session
	1,  // 3: sshproxy.v1.ListSessionsResponse.page:type_name -> sshproxy.v1.PageInfo
	31, // 4: sshproxy.v1.User.created_at:type_name -> google.protobuf.Timestamp
	31, // 5: sshproxy.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	31, // 6: sshproxy.v1.User.last_login:type_name -> google.protobuf.Timestamp
	9,  // 7: sshproxy.v1.ListUsersResponse.users:type_name -> sshproxy.v1.User
	1,  // 8: sshproxy.v1.ListUsersResponse.page:type_name -> sshproxy.v1.PageInfo
	9,  // 9: sshproxy.v1.CreateUserRequest.user:type_name -> sshproxy.v1.User
	9,  // 10: sshproxy.v1.UpdateUserRequest.user:type_name -> sshproxy.v1.User
	32, // 11: sshproxy.v1.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	30, // 12: sshproxy.v1.Server.tags:type_name -> sshproxy.v1.Server.TagsEntry
	31, // 13: sshproxy.v1.Server.checked_at:type_name -> google.protobuf.Timestamp
	14, // 14: sshproxy.v1.ListServersResponse.servers:type_name -> sshproxy.v1.Server
	1,  // 15: sshproxy.v1.ListServersResponse.page:type_name -> sshproxy.v1.PageInfo
	14, // 16: sshproxy.v1.CreateServerRequest.server:type_name -> sshproxy.v1.Server
	14, // 17: sshproxy.v1.UpdateServerRequest.server:type_name -> sshproxy.v1.Server
	32, // 18: sshproxy.v1.UpdateServerRequest.update_mask:type_name -> google.protobuf.FieldMask
	33, // 19: sshproxy.v1.ConfigDocument.config:type_name -> google.protobuf.Struct
	33, // 20: sshproxy.v1.UpdateConfigRequest.config:type_name -> google.protobuf.Struct
	31, // 21: sshproxy.v1.ConfigVersionMetadata.timestamp:type_name -> google.protobuf.Timestamp
	22, // 22: sshproxy.v1.ListConfigVersionsResponse.versions:type_name -> sshproxy.v1.ConfigVersionMetadata
	33, // 23: sshproxy.v1.ConfigVersionContent.config:type_name -> google.protobuf.Struct
	34, // 24: sshproxy.v1.SignUserCertificateRequest.force_command:type_name -> google.protobuf.StringValue
	35, // 25: sshproxy.v1.SystemService.GetHealth:input_type -> google.protobuf.Empty
	5,  // 26: sshproxy.v1.SessionService.ListSessions:input_type -> sshproxy.v1.ListSessionsRequest
	0,  // 27: sshproxy.v1.SessionService.GetSession:input_type -> sshproxy.v1.ResourceID
	0,  // 28: sshproxy.v1.SessionService.KillSession:input_type -> sshproxy.v1.ResourceID
	0,  // 29: sshproxy.v1.SessionService.GetSessionRecording:input_type -> sshproxy.v1.ResourceID
	0,  // 30: sshproxy.v1.SessionService.DownloadSessionRecording:input_type -> sshproxy.v1.ResourceID
	10, // 31: sshproxy.v1.UserService.ListUsers:input_type -> sshproxy.v1.ListUsersRequest
	0,  // 32: sshproxy.v1.UserService.GetUser:input_type -> sshproxy.v1.ResourceID
	12, // 33: sshproxy.v1.UserService.CreateUser:input_type -> sshproxy.v1.CreateUserRequest
	13, // 34: sshproxy.v1.UserService.UpdateUser:input_type -> sshproxy.v1.UpdateUserRequest
	0,  // 35: sshproxy.v1.UserService.DeleteUser:input_type -> sshproxy.v1.ResourceID
	15, // 36: sshproxy.v1.ServerService.ListServers:input_type -> sshproxy.v1.ListServersRequest
	0,  // 37: sshproxy.v1.ServerService.GetServer:input_type -> sshproxy.v1.ResourceID
	17, // 38: sshproxy.v1.ServerService.CreateServer:input_type -> sshproxy.v1.CreateServerRequest
	18, // 39: sshproxy.v1.ServerService.UpdateServer:input_type -> sshproxy.v1.UpdateServerRequest
	0,  // 40: sshproxy.v1.ServerService.DeleteServer:input_type -> sshproxy.v1.ResourceID
	35, // 41: sshproxy.v1.ServerService.GetHealthSummary:input_type -> google.protobuf.Empty
	35, // 42: sshproxy.v1.ConfigService.GetConfig:input_type -> google.protobuf.Empty
	21, // 43: sshproxy.v1.ConfigService.UpdateConfig:input_type -> sshproxy.v1.UpdateConfigRequest
	35, // 44: sshproxy.v1.ConfigService.ListConfigVersions:input_type -> google.protobuf.Empty
	24, // 45: sshproxy.v1.ConfigService.GetConfigVersion:input_type -> sshproxy.v1.GetConfigVersionRequest
	26, // 46: sshproxy.v1.ConfigService.RollbackConfig:input_type -> sshproxy.v1.RollbackConfigRequest
	35, // 47: sshproxy.v1.ConfigService.ReloadConfig:input_type -> google.protobuf.Empty
	28, // 48: sshproxy.v1.CertificateAuthorityService.SignUserCertificate:input_type -> sshproxy.v1.SignUserCertificateRequest
	35, // 49: sshproxy.v1.CertificateAuthorityService.GetCAPublicKeys:input_type -> google.protobuf.Empty
	3,  // 50: sshproxy.v1.SystemService.GetHealth:output_type -> sshproxy.v1.SystemHealth
	6,  // 51: sshproxy.v1.SessionService.ListSessions:output_type -> sshproxy.v1.ListSessionsResponse
	4,  // 52: sshproxy.v1.SessionService.GetSession:output_type -> sshproxy.v1.Session
	2,  // 53: sshproxy.v1.SessionService.KillSession:output_type -> sshproxy.v1.OperationStatus
	7,  // 54: sshproxy.v1.SessionService.GetSessionRecording:output_type -> sshproxy.v1.SessionRecordingMetadata
	8,  // 55: sshproxy.v1.SessionService.DownloadSessionRecording:output_type -> sshproxy.v1.RecordingContent
	11, // 56: sshproxy.v1.UserService.ListUsers:output_type -> sshproxy.v1.ListUsersResponse
	9,  // 57: sshproxy.v1.UserService.GetUser:output_type -> sshproxy.v1.User
	9,  // 58: sshproxy.v1.UserService.CreateUser:output_type -> sshproxy.v1.User
	9,  // 59: sshproxy.v1.UserService.UpdateUser:output_type -> sshproxy.v1.User
	2,  // 60: sshproxy.v1.UserService.DeleteUser:output_type -> sshproxy.v1.OperationStatus
	16, // 61: sshproxy.v1.ServerService.ListServers:output_type -> sshproxy.v1.ListServersResponse
	14, // 62: sshproxy.v1.ServerService.GetServer:output_type -> sshproxy.v1.Server
	14, // 63: sshproxy.v1.ServerService.CreateServer:output_type -> sshproxy.v1.Server
	14, // 64: sshproxy.v1.ServerService.UpdateServer:output_type -> sshproxy.v1.Server
	2,  // 65: sshproxy.v1.ServerService.DeleteServer:output_type -> sshproxy.v1.OperationStatus
	19, // 66: sshproxy.v1.ServerService.GetHealthSummary:output_type -> sshproxy.v1.ServerHealthSummary
	20, // 67: sshproxy.v1.ConfigService.GetConfig:output_type -> sshproxy.v1.ConfigDocument
	2,  // 68: sshproxy.v1.ConfigService.UpdateConfig:output_type -> sshproxy.v1.OperationStatus
	23, // 69: sshproxy.v1.ConfigService.ListConfigVersions:output_type -> sshproxy.v1.ListConfigVersionsResponse
	25, // 70: sshproxy.v1.ConfigService.GetConfigVersion:output_type -> sshproxy.v1.ConfigVersionContent
	2,  // 71: sshproxy.v1.ConfigService.RollbackConfig:output_type -> sshproxy.v1.OperationStatus
	2,  // 72: sshproxy.v1.ConfigService.ReloadConfig:output_type -> sshproxy.v1.OperationStatus
	29, // 73: sshproxy.v1.CertificateAuthorityService.SignUserCertificate:output_type -> sshproxy.v1.SignedCertificate
	27, // 74: sshproxy.v1.CertificateAuthorityService.GetCAPublicKeys:output_type -> sshproxy.v1.CAPublicKeys
	50, // [50:75] is the sub-list for method output_type
	25, // [25:50] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_proto_sshproxy_v1_control_plane_proto_init() }
func file_api_proto_sshproxy_v1_control_plane_proto_init() {
	if File_api_proto_sshproxy_v1_control_plane_proto != nil {
		return
	}
	file_api_proto_sshproxy_v1_control_plane_proto_msgTypes[25].OneofWrappers = []any{
		(*ConfigVersionContent_Config)(nil),
		(*ConfigVersionContent_RawContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sshproxy_v1_control_plane_proto_rawDesc), len(file_api_proto_sshproxy_v1_control_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_api_proto_sshproxy_v1_control_plane_proto_goTypes,
		DependencyIndexes: file_api_proto_sshproxy_v1_control_plane_proto_depIdxs,
		MessageInfos:      file_api_proto_sshproxy_v1_control_plane_proto_msgTypes,
	}.Build()
	File_api_proto_sshproxy_v1_control_plane_proto = out.File
	file_api_proto_sshproxy_v1_control_plane_proto_goTypes = nil
	file_api_proto_sshproxy_v1_control_plane_proto_depIdxs = nil
}
