{{- if .Values.dataPlane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-proxy-core.fullname" . }}-data-plane
  labels:
    {{- include "ssh-proxy-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-plane
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: ssh
      protocol: TCP
  selector:
    {{- include "ssh-proxy-core.dataPlane.selectorLabels" . | nindent 4 }}
{{- end }}
