{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-proxy-core.fullname" . }}-headless
  labels:
    {{- include "ssh-proxy-core.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: https
      port: {{ .Values.controlPlane.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "ssh-proxy-core.controlPlane.selectorLabels" . | nindent 4 }}
{{- end }}
