{{- if .Values.dataPlane.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ssh-proxy-core.fullname" . }}-data-plane
  labels:
    {{- include "ssh-proxy-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-plane
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ssh-proxy-core.fullname" . }}-data-plane
  minReplicas: {{ .Values.dataPlane.replicas }}
  maxReplicas: {{ mul .Values.dataPlane.replicas 4 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
{{- end }}
