apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh-proxy-core.fullname" . }}-secret
  labels:
    {{- include "ssh-proxy-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.adminToken }}
  admin-token: {{ .Values.config.adminToken | quote }}
  {{- else }}
  admin-token: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if .Values.config.ldap.enabled }}
  ldap-bind-password: {{ .Values.config.ldap.bindPassword | default "" | quote }}
  {{- end }}
  {{- if .Values.config.oidc.enabled }}
  oidc-client-secret: {{ .Values.config.oidc.clientSecret | default "" | quote }}
  {{- end }}
